### PR TITLE
Update Python C wrapping layers to new credentials API

### PR DESCRIPTION
**Pull request by soltanmm**
cc @nathanielmanistaatgoogle

(n.b. does not yet plumb it all the way through Python)

### CODE REVIEW

**Comment by jboeuf** [comment]
Thanks much. I guess that this fixes the compilation. Do the tests pass as well?

**Comment by soltanmm** [comment]
That'll be after the baton pass to Nathaniel.

**Comment by jboeuf** [comment]
Thanks for the clarification. I'll wait for Nathaniel before I merge then.

**Comment by soltanmm** [comment]
I've bandaged over the differences for now. Tests are passing.

**Comment by jboeuf** [comment]
Thanks much.

**Pull request merged**
