### PR TITLE
PHP: Core credentials API refactoring

### PR DESCRIPTION
**Pull request by stanley-cheung**
- For issue grpc/grpc#3828 and PR grpc/grpc#3765
- Split `grpc_credentials` into `grpc_channel_credentials` and `grpc_call_credentials`
- Renamed `credentials.c` into `channel_credentials.c`, `Credentials` class into `ChannelCredentials` class, etc.
- Added `call_credentials.c`, and `CallCredentials` class
- Split the original `Credentials::createComposite` function into `ChannelCredentials::createComposite` and `CallCredentials::createComposite` 
- Removed the `Credentials::createGce` method because no one is calling it
- Ran unit tests, generarted code test (against Node server with #3) and basic interop test (against Node server with #3) locally and all passed.
- There should be no more reference to the naked `Credentials` or `credentials`

### CODE REVIEW

**Comment by stanley-cheung** [comment]
@murgatroid99 Please review, thanks!

**Comment by murgatroid99** [comment]
LGTM

**Comment by jtattermusch** [comment]
is this ready for review?

**Comment by stanley-cheung** [comment]
Michael already reviewed. I suppose @jboeuf needs to review next because this will go into his major feature branch

**Comment by jboeuf** [comment]
Yes, that's on my plate. Will review tonight. Thanks much!

**Comment by jboeuf** [comment]
LGTM. Thanks much!

**Pull request merged**
